      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard - All problem
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        # - LoopTail: [False]
      ForkParameters:
        - MIArchVgpr: [True]
        - WavefrontSize: [32]
        - MatrixInstruction:
          - [16, 16, 16, 1,  1,  2,2,  2,2]  # 64x64
        - ThreadTile:
          - [ 1, 32 ]
        - WorkGroup:
          - [ 64, 4, 1 ]
        - SourceSwap: [1]
        - AssertFree0ElementMultiple: [1]
        - AssertFree1ElementMultiple: [1]
        - PrefetchGlobalRead: [1] # ,1]
        - PrefetchLocalRead: [1] # ,1] # 2,5,9]
        - DepthU: [32, 64]
        - TransposeLDS: [0, 1]
        - VectorWidth: [1, 2]
        - GlobalReadVectorWidth: [4]
#        - LocalReadVectorWidth: [8]
#        - SuppressNoLoadLoop: [0]
        - OptNoLoadLoop: [1]
        - ScheduleLocalWrite: [1]
        - ScheduleGlobalRead: [1]
        - ScheduleIterAlg: [1, 2, 3]
#        - NumElementsPerBatchStore: [0, 2]
#        - StoreSyncOpt: [0, 2]
#        - StoreSyncOpt: [0, 1]
#        - GroupLoadStore: [0, 1]
#        - InnerUnroll: [1]
#        - ExpandPointerSwap: [1]
#        - LdsBlockSizePerPad: [0]
#        - LdsPadA: [0]
#        - LdsPadB: [0]
#        - StoreRemapVectorWidth: [0]
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          # - Exact: [ 16, 16, 1 , 32 ] #gemm
          - Range: [ [256,7,320], 0, [1,1,3], [256,7,270]] #gemm
          # - Exact: [64,64,1,64]
